// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Service = require("./service.bs.js");

var pastebin = {
  selector: "a[href*=\"//pastebin.com\"]",
  embed_url: (function (url) {
      var match = url.match((/\.com\/([A-Za-z0-9]+)$/));
      if (match == null) {
        throw Service.UrlMatchFailure;
      } else if (match.length !== 2) {
        throw Service.UrlMatchFailure;
      } else {
        var id = match[1];
        return "//pastebin.com/embed_iframe/" + id;
      }
    })
};

var services = /* array */[pastebin];

exports.pastebin = pastebin;
exports.services = services;
/* No side effect */
