// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var UrlMatchFailure = Caml_exceptions.create("Service.UrlMatchFailure");

exports.UrlMatchFailure = UrlMatchFailure;
/* No side effect */
